### ISSUE TITLE
Unable to load configuration

### ISSUE THREAD

**Issue by dvdvideo1234** [osule/offline-ytube#6]
```
deyan@deyan-vb:~/Documents/UbuntuBatches/youtube/offline-tube$ sudo ./bin/run
[2018-04-02 14:35:34 +0000] [3909] [INFO] Starting gunicorn 19.7.1
[2018-04-02 14:35:34 +0000] [3909] [INFO] Listening at: http://127.0.0.1:8000 (3909)
[2018-04-02 14:35:34 +0000] [3909] [INFO] Using worker: sync
[2018-04-02 14:35:34 +0000] [3913] [INFO] Booting worker with pid: 3913
[2018-04-02 14:35:34 +0000] [3913] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/deyan/Documents/UbuntuBatches/youtube/offline-tube/web/manage.py", line 1, in <module>
    from web.setup import app, sse
  File "/home/deyan/Documents/UbuntuBatches/youtube/offline-tube/web/setup.py", line 5, in <module>
    app, sse = factory.create_app()
  File "/home/deyan/Documents/UbuntuBatches/youtube/offline-tube/web/factory.py", line 15, in create_app
    app.config.from_pyfile(pyfile)
  File "/usr/local/lib/python2.7/dist-packages/flask/config.py", line 129, in from_pyfile
    with open(filename) as config_file:
IOError: [Errno 2] Unable to load configuration file (No such file or directory): '/home/deyan/Documents/UbuntuBatches/youtube/offline-tube/web/../.env'
[2018-04-02 14:35:34 +0000] [3913] [INFO] Worker exiting (pid: 3913)
[2018-04-02 14:35:34 +0000] [3909] [INFO] Shutting down: Master
[2018-04-02 14:35:34 +0000] [3909] [INFO] Reason: Worker failed to boot.
```

**Comment by dvdvideo1234** [comment]
```bash
deyan@deyan-vb:~/Documents/UbuntuBatches/youtube/offline-tube$ echo "" >> .env
```
When I create `.env` file via `echo "" >> .env` I get:
```bash
deyan@deyan-vb:~/Documents/UbuntuBatches/youtube/offline-tube$ ./bin/run
[2018-04-02 14:40:37 +0000] [3976] [INFO] Starting gunicorn 19.7.1
[2018-04-02 14:40:37 +0000] [3976] [INFO] Listening at: http://127.0.0.1:8000 (3976)
[2018-04-02 14:40:37 +0000] [3976] [INFO] Using worker: sync
[2018-04-02 14:40:37 +0000] [3980] [INFO] Booting worker with pid: 3980
[2018-04-02 14:40:38 +0000] [3980] [ERROR] invalid syntax (utils.py, line 8)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/deyan/Documents/UbuntuBatches/youtube/offline-tube/web/manage.py", line 2, in <module>
    from web.routes import register_blueprints
  File "/home/deyan/Documents/UbuntuBatches/youtube/offline-tube/web/routes.py", line 2, in <module>
    from .blueprints import api, home
  File "/home/deyan/Documents/UbuntuBatches/youtube/offline-tube/web/blueprints/__init__.py", line 1, in <module>
    from .api import blueprint as api
  File "/home/deyan/Documents/UbuntuBatches/youtube/offline-tube/web/blueprints/api/__init__.py", line 2, in <module>
    from .views import create_views
  File "/home/deyan/Documents/UbuntuBatches/youtube/offline-tube/web/blueprints/api/views.py", line 4, in <module>
    from .utils import search_video, get_media_types, get_task_status
  File "/home/deyan/Documents/UbuntuBatches/youtube/offline-tube/web/blueprints/api/utils.py", line 8
    request, *rest = args
             ^
SyntaxError: invalid syntax
[2018-04-02 14:40:38 +0000] [3980] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 148, in load_wsgi
    self.reloader.add_extra_file(exc_val.filename)
AttributeError: 'NoneType' object has no attribute 'add_extra_file'
[2018-04-02 14:40:38 +0000] [3980] [INFO] Worker exiting (pid: 3980)
[2018-04-02 14:40:38 +0000] [3976] [INFO] Shutting down: Master
[2018-04-02 14:40:38 +0000] [3976] [INFO] Reason: Worker failed to boot.
```

**Comment by osule** [comment]
@dvdvideo1234 Thanks for checking out this project. I'm developing this project in Python 3.

Sadly, it isn't at a stage for consumption or contribution yet. I'll write a disclaimer in the README about the errors that may occur.
